feat: GCS setup and modification of the URLField to ImageField
RevelioStartup/revelio-be pull request #16
Opened 2024-03-02 13:05 UTC by nataniadeandra

**Summary of Changes:**

1. **Google Cloud Storage Setup:** Integrated the backend with Google Cloud Storage. This was achieved by adding the `dotted-lexicon-415505-86934bc0f37c.json` file, which contains the necessary credentials, and updating the settings with the appropriate credentials and bucket name.

2. **Photo Model Update:** Modified the Photo model in `venue/models.py`. The field previously using `URLField` has been changed to `ImageField`. This adjustment is crucial for the integration with Google Cloud Storage. The URLs in Google Cloud Storage are dynamic and can change over time. By managing the image references directly in the backend, we ensure that the frontend always receives valid and current image URLs, thereby reducing the risk of broken links.

3. **Test Modification:** Aligned the tests in `venue/tests.py` with the changes made in the Photo model. This ensures that our tests remain valid and continue to provide valuable feedback on the functionality of our application.

4. **Image Addition for Testing:** Added an image file named `empathymap.jpg` for testing purposes. This image will be used to validate the functionality of the updated Photo model and the integration with Google Cloud Storage.

5. **Test Case Refactoring:** Refactored the base test cases for the Venue and Photo models in `venue/tests.py`. The tests for these two models are now separate, making them clearer and easier to read. This change improves the maintainability of our tests and makes it easier to identify and fix issues in the future.

2024-03-02 13:11 UTC, catherineeangel approved these changes
Nice, by implementing GCS directly it will ease the storage consumption of our app. Overall the code looks good and the tests covered all the possible cases

2024-03-02 13:13 UTC, emiriko reviewed
I really like your approaches and refactoring; it looks good and efficient. Keep up the good work!

2024-03-02 13:13 UTC, emiriko commented on dotted-lexicon-415505-86934bc0f37c.json
Personally, I think this needs to not be pushed to github, as our repository is public and this file contains sensitive information. What does everyone think?

2024-03-02 13:43 UTC, catherineeangel commented on dotted-lexicon-415505-86934bc0f37c.json
Right, are there any other way to do so? can we put the filename as an enviroment variable and refer it from the .env ?

2024-03-02 14:18 UTC, JohannesSetiawan requested changes
Everything looks good except the sensitive information in the .json. Should be disclosed. Even better if you can revert to commit to that .json so it wont appear in the commit history.

2024-03-02 14:18 UTC, JohannesSetiawan commented on dotted-lexicon-415505-86934bc0f37c.json
Yeah this is a very sensitive information, should be put on the environment variables.

2024-03-02 14:48 UTC, nataniadeandra commented on dotted-lexicon-415505-86934bc0f37c.json
I completely understand everyone's perspectives. I acknowledge that I may have overlooked the fact that storing sensitive data in GitHub secrets is not a recommended practice.

@catherineeangel @JohannesSetiawan, your idea to use GitHub environment variables and generate the `.json` file during the build process is excellent. Will revert and implement all of your suggestions. Thank you. ☺️

2024-03-03 11:43 UTC, swastikanata approved these changes
Agree with others above, everything should be fine after you hide the private information with environment secrets.Other than that, look good to me.

2024-03-06 10:23 UTC, nataniadeandra commented
Hello, I have moved all the necessary credentials for Google Cloud Storage from the earlier files to environment variables in Github and Vercel. I kindly request those who have previously commented or requested changes to either approve this pull request or provide additional feedback if necessary.

@swastikanata @catherineeangel @JohannesSetiawan @emiriko @carlenee

2024-03-09 03:13 UTC, JohannesSetiawan approved these changes

2024-03-09 03:23 UTC, JohannesSetiawan approved these changes
Good. The problem is fixed.

2024-03-12 00:55 UTC, merged