Logic Update for Mengubah Step By Step
RevelioStartup/revelio-be pull request #36
Opened 2024-04-01 11:53 UTC by swastikanata

When updating status for steps, update status for task as well

2024-04-01 14:03 UTC, carlenee submitted a review, later dismissed
can you add the get api for the task steps that was deleted or maybe not if it's not necessary anymore? whatever suits our project more thank you

2024-04-02 02:18 UTC, JohannesSetiawan requested changes
Overall it looks good. But might want to do some checking first

2024-04-02 02:18 UTC, JohannesSetiawan commented on task_steps/views.py
I guess for task instance, the status is "Not Started", "On Progress", and "Done" not NOT_STARTED, ON_PROGRESS, DONE. Might want to check wether Line 108 - 113 really works as expected.

2024-04-02 11:31 UTC, JohannesSetiawan approved these changes

2024-04-02 15:56 UTC, catherineeangel approved these changes
LGTM

2024-04-03 00:31 UTC, merged